### ISSUE TITLE
А можно чтоб под симулятором тоже заводилось?

### ISSUE THREAD

**Issue by yury** [LiveTex/Livetex-iOS-SDK-Demo#1]
Вот такие вот ошибки при билде:
```
ld: warning: directory not found for option '-L/Users/yury/Library/Developer/Xcode/DerivedData/LTMobileSDK-gobsmgafmedlnthgewbmoplmtqum/Build/Products/Debug-iphoneos'
ld: warning: ignoring file /Users/yury/Projects/Livetex-iOS-SDK-Demo/LiveTex_SDK_Demo/Livetex_SDK/libLTMobileSDK.a, missing required architecture x86_64 in file /Users/yury/Projects/Livetex-iOS-SDK-Demo/LiveTex_SDK_Demo/Livetex_SDK/libLTMobileSDK.a (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_LTMobileSDK", referenced from:
      __TMaCSo11LTMobileSDK in LTAuthorizationViewController.o
      __TMaCSo11LTMobileSDK in AppDelegate.o
      __TMaCSo11LTMobileSDK in LTApiManager.o
  "_OBJC_CLASS_$_LTMobileSDKInitializationParams", referenced from:
      __TMaCSo31LTMobileSDKInitializationParams in LTAuthorizationViewController.o
      __TMaCSo31LTMobileSDKInitializationParams in AppDelegate.o
  "_OBJC_CLASS_$_LTSAbuse", referenced from:
      __TMaCSo8LTSAbuse in LTClaimingViewController.o
  "_OBJC_CLASS_$_LTSDepartment", referenced from:
```

**Comment by SergeyDLivetex** [comment]
На текущий момент в планах нету реализации данной просьбы.

**Comment by ivampir** [comment]
А дебажить то как вы предлагаете? Типа после включения вашей библиотеки в проект у меня пропадает возможность дебажить в симуляторе?!

**Comment by ivampir** [comment]
И неплохо было бы написать на Objective-C, и сделать универсальный сториборд.

**Comment by SergeyDLivetex** [comment]
Сама библиотека написана на Objective-C. То, что демо написано на Swift, какие сложности это вызывает? 
В новой версии демо-приложения, которая скоро выйдет, будет универсальный storyboard.

**Comment by SergeyDLivetex** [comment]
Дебажить на данный момент предлагается на девайсе, проблем с дебагом в этом случае нету. Вопрос удобства использования симулятора не игнорируется, в скором времени добавим версию библиотеки для него.

**Comment by DmitryTsepelev** [comment]
Проблема не в том, чтоб дебажить работу с вашей библиотекой, а в том, чтобы дебажить остальную часть приложения.

**Comment by SergeyDLivetex** [comment]
Добавлена версия для симулятора в соответствующей ветке.
